package com.pengxh.secretkey.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.pengxh.secretkey.bean.SecretSQLiteBean;

import com.pengxh.secretkey.greendao.SecretSQLiteBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig secretSQLiteBeanDaoConfig;

    private final SecretSQLiteBeanDao secretSQLiteBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        secretSQLiteBeanDaoConfig = daoConfigMap.get(SecretSQLiteBeanDao.class).clone();
        secretSQLiteBeanDaoConfig.initIdentityScope(type);

        secretSQLiteBeanDao = new SecretSQLiteBeanDao(secretSQLiteBeanDaoConfig, this);

        registerDao(SecretSQLiteBean.class, secretSQLiteBeanDao);
    }
    
    public void clear() {
        secretSQLiteBeanDaoConfig.clearIdentityScope();
    }

    public SecretSQLiteBeanDao getSecretSQLiteBeanDao() {
        return secretSQLiteBeanDao;
    }

}
